### ISSUE TITLE
API change has broken pymyq

### ISSUE THREAD

**Issue by Bahnburner** [arraylabs/pymyq#20]
Something in the API has changed and is preventing authentication. 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in main
  File "/home/titan/.local/lib/python3.6/site-packages/pymyq/api.py", line 291, in login
    await api.authenticate(username, password)
  File "/home/titan/.local/lib/python3.6/site-packages/pymyq/api.py", line 226, in authenticate
    await self._get_security_token()
  File "/home/titan/.local/lib/python3.6/site-packages/pymyq/api.py", line 242, in _get_security_token
    login_request=True,
  File "/home/titan/.local/lib/python3.6/site-packages/pymyq/api.py", line 151, in _request
    return await resp.json(content_type=None)
  File "/home/titan/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 1036, in json
    return loads(stripped.decode(encoding))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by towerhand** [comment]
Same here.

**Comment by jschwalbe** [comment]
+1
There is a new app as well, it appears. :\

**Comment by brbeaird** [comment]
All is not lost - you can still auth fine manually, so it's possible to get this fixed. I made some tweaks to the SmartThings  version after it broke today, and it's working again.

It's likely an issue with the app_id and possibly the user agent (which may not even be required any more).

I'd do testing myself but all my systems have python 2.7, and I can't cleanly mess with this at the moment.

**Comment by ehendrix23** [comment]
> All is not lost - you can still auth fine manually, so it's possible to get this fixed. I made some tweaks to the SmartThings version after it broke today, and it's working again.
> 
> It's likely an issue with the app_id and possibly the user agent (which may not even be required any more).
> 
> I'd do testing myself but all my systems have python 2.7, and I can't cleanly mess with this at the moment.

Do you mind stating what you changed? That would then give a start for testing.

Thx.

**Comment by brbeaird** [comment]
Looks like you got it - nicely done.

**Comment by ehendrix23** [comment]
> Looks like you got it - nicely done.
Yep, found your GitHub and was thus able to see what you changed. :-) Thanks for that as that truly helped me out!!!

**Comment by mikeboiko** [comment]
Excellent, thanks for fixing. When will HA will roll out this update in official release?

**Comment by ehendrix23** [comment]
Hopefully in the next patch version.

**Comment by mikeboiko** [comment]
Great, thanks :D
