### ISSUE TITLE
Suddenly JSONDecodeError

### ISSUE THREAD

**Issue by dseven** [arraylabs/pymyq#34]
Suddenly, at 2020-05-05 16:11:45 UTC, home assistant stopped being able to track my garage door. I find this in its log:

```
2020-05-05 09:11:45 ERROR (MainThread) [homeassistant.components.myq] Unexpected error fetching myq devices data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 140, in update_device_info
    "get", "Accounts/{0}/Devices".format(self.account_id)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 83, in request
    data = await resp.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Using the simple "To get all MyQ devices associated with an account" test from the README fails the same way:

```
Traceback (most recent call last):
  File "testmyq.py", line 22, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "testmyq.py", line 11, in main
    myq = await pymyq.login('myqdevice@mydomain.com', 'xxx', websession)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 167, in login
    await api.authenticate(username, password)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 124, in authenticate
    await self.update_device_info()
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 140, in update_device_info
    "get", "Accounts/{0}/Devices".format(self.account_id)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 83, in request
    data = await resp.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by broyuken** [comment]
I’m seeing similar issues today

home-assistant/core#35257

**Comment by bdraco** [comment]
@arraylabs 

I've got it working again.  I'll send a PR shortly

**Comment by 88gts** [comment]
resolved the issue for me, thank you.

**Comment by pcpimp** [comment]
Hello, I'm guessing the API has changed again? I'm getting the same issue just started around 7:00 PM EST.

**Comment by dseven** [comment]
Something's b0rked again, but it's not the same as before. I'm getting the below exception in HA, but, curiously, cannot seem to reproduce it outside HA so-far.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/myq/__init__.py", line 36, in async_setup_entry
    myq = await pymyq.login(conf[CONF_USERNAME], conf[CONF_PASSWORD], websession)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 170, in login
    await api.authenticate(username, password)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 119, in authenticate
    self._security_token = auth_resp["SecurityToken"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by NickNothom** [comment]
> Hello, I'm guessing the API has changed again? I'm getting the same issue just started around 7:00 PM EST.

Same. [Issue here](https://github.com/arraylabs/pymyq/issues/38)
